# Generated by Django 3.1 on 2020-08-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='總金額')),
                ('amount', models.IntegerField(verbose_name='票卷張數')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='購買日期與時間')),
            ],
        ),
    ]
